// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Link.Pokedex.Api.Infrastructure.Data.Entities
{
    public partial class Tipo
    {
        public int IdTipo { get; set; }
        public string Nombre { get; set; }
        public string ClaseColor { get; set; }
    }
}