// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Link.Pokedex.Utility
{
    public partial class Pokemon
    {
        public int IdPokemon { get; set; }
        public string Nombre { get; set; }
        public decimal? Altura { get; set; }
        public string Categoria { get; set; }
        public decimal? Peso { get; set; }
        public string Habilidad { get; set; }
        public string Sexo { get; set; }
        public int? Ps { get; set; }
        public int? Ataque { get; set; }
        public int? Defensa { get; set; }
        public int? AtaqueEspecial { get; set; }
        public int? DefensaEspecial { get; set; }
        public int? Velocidad { get; set; }
        public string Imagen { get; set; }
    }
}